// app/src/components/Footer.tsx
import React from 'react';
import Link from 'next/link';

const Footer: React.FC = () => {
  return (
    <footer className="bg-black text-gray-400 text-center py-5 text-lg">
      <ul className="list-none p-0 m-0 flex justify-center space-x-4">
        <li>
          <Link
            href="/copyright/"
            className="text-sm text-white transition-colors duration-300"
          >
            掲載情報について
          </Link>
        </li>
        <li>
          <Link
            href="/disclaimer/"
            className="text-sm text-white transition-colors duration-300"
          >
            免責事項
          </Link>
        </li>
        <li>
          <Link
            href="/privacy/"
            className="text-sm text-white transition-colors duration-300"
          >
            プライバシーポリシー
          </Link>
        </li>
        <li>
          <Link
            href="/inquiry/"
            className="text-sm text-white transition-colors duration-300"
          >
            お問い合わせ
          </Link>
        </li>
      </ul>
      <div className="m-0">
        <p className="text-gray-400 m-0">
          <small>&copy; {new Date().getFullYear()} Akitoshi Saeki</small>
        </p>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer class="footer">
    <ul class="footer_links">
      <li class="link">
        <nuxt-link :to="`/copyright`">掲載情報について</nuxt-link>
      </li>
      <li class="link">
        <nuxt-link :to="`/disclaimer`">免責事項</nuxt-link>
      </li>
      <li class="link">
        <nuxt-link :to="`/privacy`">プライバシーポリシー</nuxt-link>
      </li>
      <li class="link">
        <nuxt-link :to="`/inquiry`">お問い合わせ</nuxt-link>
      </li>
    </ul>
    <div class="wrapper">
      <p class="copyright_text"><small>© 2023 Akitoshi Saeki</small></p>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  background-color: #101010;
  text-align: center;
  padding: 2rem 1rem;
  color: #dbdbdb;
  font-size: 1.1rem; /* 0.9remから1.1remに変更 */
}

.wrapper {
  max-width: 1100px;
  margin: 0 auto;
}

.copyright_text {
  margin-top: 1rem;
}

.footer_links {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.link {
  display: inline-block;
  margin: 0 0.5rem;
}

.link:not(:last-child)::after {
  content: "|";
  color: #b5b5b5;
  margin-left: 0.5rem;
}

.link a {
  color: #dbdbdb;
  transition: color 0.3s;
}

.link a:hover {
  color: #fff;
}
</style>
